Act I: Id
---------

*Id* is the set of uncoordinated instinctual trends in the human psyche.

This part of the guide focuses on the philosophy behind great code.

-
-


Act II: Ego
-----------

*Ego* is the organized and realistic role of the human psyche.

This part of the guide focuses on best practices for organizing and writing code.

- obvious benefit (constraints foster creativity)
- lawyer up
- README
- LICENSE


Act III: Super-ego
------------------

*Super-ego* is the critical and moralizing role of the human psyche.

This part of the guide focuses on the ethos of great code communities.

- Clarity is Key
- Documentation
- Community
- Contributions and BDFL
- Code of Conduct


--------------------


Appendix A: Resources
---------------------

For further reading...

- Semantic Versioning
- The Architecture of Open Source Applications
- *&c*

Appendix B: Meta
----------------

Contibution notes and legal information are here (for those interested).

.. toctree::
   :maxdepth: 2

   notes/contribute
   notes/license
   notes/styleguide
