Act I: Id
---------

This part of the guide focuses on...

.. toctree::
   :maxdepth: 2

- Consistency
- Clarity
- API-Driven Development?



Act II: Ego
-----------

This part of the guide focuses on best practices for writing code.

- obvious benefit (constraints foster creativity)
- lawyer up
- README
- LICENSE


Act III: Super-ego
------------------

- Clarity is Key
- Documentation
- Community
- Contributions and BDFL
- Code of Conduct


--------------------------------------

Contibution notes and legal information are here (for those interested).

.. toctree::
   :maxdepth: 2

   notes/contribute
   notes/license
   notes/styleguide
