Getting Started
---------------

This part of the guide focuses on setting up your Python environment.

.. toctree::
   :maxdepth: 2



- Properly Install Python



Writing Great Code
------------------

This part of the guide focuses on best practices for writing Python code.




Scenario Guide
--------------

This part of the guide focuses on tool and module advice based on
different scenarios.




Shipping Great Code
-------------------

This part of the guide focuses on deploying your Python code.



Development Environment
-----------------------




Additional Notes
----------------

This part of the guide, which is mostly prose, begins with some
background information about Python, then focuses on next steps.





--------------------------------------

Contibution notes and legal information are here (for those interested).

.. toctree::
   :maxdepth: 2

   notes/contribute
   notes/license
   notes/styleguide
